# vim:ft=kitty
## Gruvbox Material Dark Hard colors for kitten diff.

color_scheme dark
dark_pygments_style gruvbox-dark

dark_background #1d2021
dark_foreground #d4be98

dark_title_bg #1d2021
dark_title_fg #d4be98

dark_margin_bg #171a1a
dark_margin_fg #928374

dark_removed_bg #3c2528
dark_highlight_removed_bg #5a2e31
dark_removed_margin_bg #5a2e31

dark_added_bg #2d3324
dark_highlight_added_bg #3f4a2b
dark_added_margin_bg #3f4a2b

dark_moved_bg #263838
dark_moved_margin_bg #324f52

dark_filler_bg #171a1a
dark_margin_filler_bg #171a1a

dark_hunk_bg #252b2a
dark_hunk_margin_bg #3c3836

dark_search_bg #d8a657
dark_search_fg #1d2021
dark_select_bg #7daea3
dark_select_fg #1d2021
