shell zsh

# Open scrollback buffer in Neovim (or change 'nvim' to 'vim' or 'less')
scrollback_pager nvim -c "set nonumber nolist showtabline=0 foldcolumn=0|autocmd TermOpen * startinsert" -c "autocmd TermClose * call cursor(max([0,INPUT_LINE_NUMBER-1])+CURSOR_LINE, CURSOR_COLUMN)" -c "terminal sed </dev/fd/63 -e 's/"$'\E'R".*//'"
map ctrl+shift+h show_scrollback

# Press Ctrl+Shift+P to highlight any file path on screen and copy it
map ctrl+shift+p kitten hints --type path --program @ 

# Press Ctrl+Shift+T to highlight ROS2 topics (regex: starts with / and has lowercase/underscores)
map ctrl+shift+t kitten hints --type regex --regex "(?m)^/[-a-zA-Z0-9_]+(/[a-zA-Z0-9_]+)*" --program @

# Press F11 to toggle broadcasting keystrokes to all panes in the current tab
map f11 toggle_marker iregex 1 \\bERROR\\b 
map f11 launch --allow-remote-control kitty +kitten broadcast

# Press Ctrl+Shift+Z to toggle the current pane to full screen (stack) and back
map ctrl+shift+z toggle_layout stack

allow_remote_control yes
listen_on unix:/tmp/kitty

# Open clicked file paths in Neovim
open_url_with nvim

# Neovim / Kitty Window Navigation
allow_remote_control yes
listen_on unix:@mykitty

map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right
map --when-focus-on var:IS_VIM=true ctrl+h
map --when-focus-on var:IS_VIM=true ctrl+j
map --when-focus-on var:IS_VIM=true ctrl+k
map --when-focus-on var:IS_VIM=true ctrl+l

# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME
