os_window_state maximized

# Development tab
new_tab DEV
layout grid
launch zsh -ic "dcup && dcinw"
launch zsh -ic "dcinw nvim"
launch zsh -ic "dcinw codex"
launch zsh -ic "dcinw claude"

# Runtime tab
new_tab RUNTIME
layout grid
launch zsh -ic "dcinw"
launch zsh -ic "dcinw"
launch zsh -ic "dcinw"
launch zsh -ic "dcinw"
